---
abstract: 'A POE component to retrieve recent CPAN uploads.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Date: 0
  HTTP::Response: 0
  Test::More: 0.47
  Test::POE::Server::TCP: 0.14
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Recent
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  POE::Component::SmokeBox::Recent:
    file: lib/POE/Component/SmokeBox/Recent.pm
    version: 1.32
  POE::Component::SmokeBox::Recent::FTP:
    file: lib/POE/Component/SmokeBox/Recent/FTP.pm
    version: 1.32
  POE::Component::SmokeBox::Recent::HTTP:
    file: lib/POE/Component/SmokeBox/Recent/HTTP.pm
    version: 1.32
requires:
  CPAN::Recent::Uploads: 0.06
  HTTP::Request: 0
  POE: 0.38
  POE::Component::Client::DNS: 1.02
  POE::Filter::HTTP::Parser: 1.06
  Test::POE::Client::TCP: 0.08
  URI: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-smokebox-recent/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/bingos/poe-component-smokebox-recent.git
    web: http://github.com/bingos/poe-component-smokebox-recent/tree
version: 1.32
