---
abstract: 'A POE component to retrieve recent CPAN uploads.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
  Test::POE::Server::TCP: 0.14
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Recent
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  HTTP::Request: 0
  POE: 0.38
  POE::Component::Client::HTTP: 0.82
  Test::POE::Client::TCP: 0.08
  URI: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.02
