---
abstract: 'A POE component to retrieve recent CPAN uploads.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  HTTP::Date: 0
  HTTP::Response: 0
  Test::More: 0.47
  Test::POE::Server::TCP: 0.14
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Recent
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  HTTP::Request: 0
  POE: 0.38
  POE::Component::Client::DNS: 1.02
  POE::Filter::HTTP::Parser: 0.08
  Test::POE::Client::TCP: 0.08
  URI: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-smokebox-recent.git
version: 1.14
